apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-generator-serviceaccount
  namespace: namespace-usage-report
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: report-generator-role
  namespace: namespace-usage-report
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "limitranges", "resourcequotas"]
    verbs:
      - list
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: report-generator-rolebinding
  namespace: namespace-usage-report
subjects:
- kind: ServiceAccount
  name: report-generator-serviceaccount
  namespace: namespace-usage-report
roleRef:
  kind: ClusterRole
  name: report-generator-role
  apiGroup: rbac.authorization.k8s.io
